export const skills = [
    "React",
    "React Hooks",
    "React Router",
    "NPM",
    "Redux",
    "Redux (Toolkit)",
    "Redux-Saga",
    "GitHub Pull Requests & Review",
    "Git",
    "Working with API (fetch, axios)",
    "Promises, Async/Await",
    "Error handling",
    "ES6+",
    "Semantic & accessible HTML",
    "Responsive Web Design",
    "Immutability",
    "CSS Flexbox",
    "CSS Grid",
    "CSS BEM convention",
    "Markdown",
    "Trello",
    "Scrum basic knowledge",
    "WordPress basic knowledge", 
  ];
  
  export const toLearn = [
    "TypeScript", 
    "Python", 
    "Node.js",
    "SQL",
    "MongoDB",
    "Mongoose",
  ];